apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tt-replicaset
  labels:
    app: python-and-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-and-exporter
  template:
    metadata:
      labels:
        app: python-and-exporter
    spec:
      containers:
      - name: python-container
        image: ghcr.io/ccc909/proiect_tt:latest
        ports:
        - containerPort: 80
        - containerPort: 9100
---

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tt-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-and-exporter
  endpoints:
  - port: metrics
    interval: 30s

---
apiVersion: v1
kind: Service
metadata:
  name: tt-service
  labels:
    app: python-and-exporter
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9100
    targetPort: 9100
  selector:
    app: python-and-exporter
